### ISSUE TITLE
Sunset docs for soon-to-be-deprecated projects

### ISSUE THREAD

**Issue by LauraLangdon** [suborbital/docs#171]
NB: all renaming will happen in a future PR. 😊

With the transition away from Atmo, we'll no longer be directing users' attention to Vektor, Grav, and Reactr. Subo isn't being deprecated, of course, but docs for using Subo with particular products will move out of a Subo category and integrate into the product docs (except for the install page, since that's the same for everything Subo).

None of the Vektor pages are referred to by any other pages, so they can safely be removed.

Of the four Reactr pages, only the language support and Reactr ❤️ Wasm pages are currently referred to outside of the Reactr category. ~~It's not yet obvious whether the language support page should be moved to Compute or to Atmo, nor whether the Reactr ❤️ Wasm page (referred to on [Subo -> Usage](https://docs.suborbital.dev/subo/usage)) should be absorbed into another category or be deleted.~~ The language support page will move to Atmo, and I deleted the reference to Reactr from the Subo -> Usage page, so it can be removed.

None of the Grav pages are referred to by pages outside of Grav, so they can also be removed easily.

The Subo -> Usage page overlapped enormously with Atmo -> Get Started, so I combined them and Subo -> Usage can be removed.

~~Given all that's disappearing, we'll also no longer need a glossary.~~ @hola-soy-milk made a great case for keeping an Atmo glossary, so I've removed references to deprecating projects and moved the glossary into Atmo.

**Comment by hola-soy-milk** [comment]
I'd love to recommend keeping the glossary in some form, or definitely bring in a new one, seeing as the [`Appspec`](https://github.com/suborbital/appspec#deltav-system-spec) lists a set of terms that I would need a glossary for

**Comment by LauraLangdon** [comment]
My thinking has changed on this! I'm now thinking that we should make word meanings clear in situ, like shift the burden of making vocabulary clear to *us* as we're writing instead of putting it on the reader to go looking for a glossary. I'd love to hear what you think about doing it that way, @hola-soy-milk!

**Comment by hola-soy-milk** [comment]
My first thought is: Why not have both?

The purpose of the glossary is to have the reader pop over if they see a term and need a quick refresher of what it means. Say, they've read it earlier and instead of having to scroll back to the definition. 

Or did I misunderstand? Are you saying we can make the terms like [Tenant](https://github.com/suborbital/appspec#deltav-system-spec) clear from context, or that we should change them?

**Comment by hola-soy-milk** [comment]
The separation of glossaries sounds grand.

I'm afraid I'm also struggling from a language standpoint, as tenants refer to humans renting resources, making it a metaphor in this context, which is okay, but when it comes to English as a second language, I would prefer to be one hundred percent sure what something means in a specific context, and I'm not sure this can be done by implication. I'm probably overthinking this.

I see the conflict of having a glossary implying there's a complex nature in the terms, but I'm also a fan of having a central place to hop in and quickly look things up. It's not something I often need, but when I do, it's indispensible. In fact, I'd even go as far as to say that maybe it seems complex because well, Wasm-based plugins are. If [GitHub](https://docs.github.com/en/get-started/quickstart/github-glossary), [Deno Depoy](https://deno.com/deploy/subhosting/docs/glossary) (which is in a similar space), [React](https://en.reactjs.org/docs/glossary.html) and other projects have glossaries for their complex terms, I think the same applies here, too.

I don't want to be a blocker on this, but I'm in favour of keeping a glossary. The argument I'd see for the contrary is that being able to search documentation nullifies the need for it. Would that make it superfluous/difficult to maintain? I'm not sure.

**Comment by LauraLangdon** [comment]
I think everything you said makes perfect sense, and I appreciate you calling out ESL readers' needs especially 🤗. And thanks for the links to those glossaries! It looks like Deno's glossary isn't linked in the top-level docs categories (which is why I didn't see it!), and is only shown in the subcategory to which is belongs, so that feels like confirmation that doing the same for DeltaV would be a solid move.

I'm still hoping to not need one for Compute, but what do you think?
