### ISSUE TITLE
Discussion on whether to include all flavours of npm install or just npm

### ISSUE THREAD

**Issue by javorszky** [suborbital/docs#43]
npm, yarn, pnmp

npm comes default with node installed. People who install yarn or pnpm have gone out of their way to deviate from the default, so the assumption is that they know how a given npm command looks like in their choice of package manager.

That means we could reduce noise by omitting command examples that relate to yarn or pnpm.

On the other hand that might make it harder for newer devs to work with the documentation especially if they were advised to install yarn as a first thing after installing node when they began their developer journey.

**Comment by ramonh** [comment]
Tricky question, thanks for asking!

My gut says we could have little tabs for different installation methods. However, this is tricky to mantain.

How about a `note` that says this is written with npm in mind, but works on package manager of choice?

**Comment by LauraLangdon** [comment]
I also wrote about this in my onboarding notes, feeling like we should either stick with just npm or provide a link to an explanation about why someone might choose one or the other. I also like @ramonh's suggestion: 
> How about a `note` that says this is written with npm in mind, but works on package manager of choice?

**Comment by flaki** [comment]
I'd be down for a tabbed component approach, however, to my understanding, Yarn will complain about having npm-specific lockfiles (`package-lock.json`) in the folder when installing because that's a possible footgun as (locked) dependencies could go inconsistent between using two systems -- and the `package-lock.json` we currently have (as per industry best practice) committed into the repo, so it will *always* be there by default. So avoiding this would require more research to figure out what's the correct best practice here.

TBQH the digging I did for #12 uncovered practical gains for why someone would want to use Yarn so I wouldn't throw it away just yet.

**Comment by hola-soy-milk** [comment]
Going by my conversation with @callahad:

> Those who know `yarn` will use `yarn`

Making the conclusion here that we'll remove the yarn mentions and stick with `npm` for now
